/**
 * The cc-shim fragment that routes every terminal `claude` through the wire —
 * the "routing" half of `enable`.
 *
 * A native `.mjs` fragment: the shim runs it in a worker thread on macOS, Linux
 * and Windows alike, and imports the environment it leaves (cc-shim docs/reference.md, "The
 * conf.d contract"). Sorts as 05-, early, and claims — so when the gateway
 * answers, no later fragment runs and the launch goes to :4747. When the gateway
 * is down it exits without claiming and whatever comes next takes the launch;
 * with nothing next, claude uses its own login. Nothing here can strand a launch.
 *
 * Generated, not hand-edited: `enable` (or `shim on`) writes it, `disable` (or
 * `shim off`) removes it, and the rev in the header is how a stale copy is
 * recognised. It replaced `05-brain-gateway.sh` (rev 4: bash, /dev/tcp and
 * curl); writing this one removes that one, which would otherwise sort first and
 * claim.
 */
import { chmodSync, existsSync, mkdirSync, readFileSync, unlinkSync, writeFileSync } from "node:fs"
import { join } from "node:path"
import { DISPLAY_NAME, configDir } from "./brand.ts"
import { command as gw } from "./command.ts"
import { CLAUDE_ENV } from "./claude-env.ts"
import type { Config } from "./config.ts"

export const FRAGMENT_REV = 5
export const FRAGMENT_NAME = "05-gateway.mjs"
/** The bash fragment rev 4 and before wrote; removed on sight. */
export const LEGACY_FRAGMENT_NAME = "05-brain-gateway.sh"

/** Where cc-shim reads fragments: <configDir>/cc-shim/conf.d (%APPDATA% on Windows). */
export const fragmentDir = (): string => join(configDir(), "cc-shim", "conf.d")
export const fragmentPath = (): string => join(fragmentDir(), FRAGMENT_NAME)
export const legacyFragmentPath = (): string => join(fragmentDir(), LEGACY_FRAGMENT_NAME)

export function renderFragment(cfg: Config): string {
  const q = JSON.stringify
  return `// ${FRAGMENT_NAME} — GENERATED by \`${gw("enable")}\`. rev ${FRAGMENT_REV}
// Regenerated when the rev changes; edit gateway/src/shim.ts rather than this file.
//
// Routes claude at the ${DISPLAY_NAME} gateway (the harness's wire), which traces the
// request, applies policy, and injects the credential of the account it picks.
// Sorts early and claims, so no later fragment routes the launch elsewhere.
//
// Fails open: gateway down -> exit without claiming -> the next fragment runs,
// or claude uses its own login. \`${gw("disable")}\` removes this file.
// A cc-shim fragment: it runs in a worker, and only the process.env it leaves is
// imported — process.exit() here ends this fragment, never the launch.
import { basename } from "node:path"

const host = ${q(cfg.host)}
const port = ${Number(cfg.port)}
const env = process.env
let base = \`http://\${host}:\${port}\`

// Up means the gateway answers its health check. This runs on every claude
// invocation, \`--version\` and SDK subprocesses too: a refused connection
// answers at once, and a wedged one is given a second.
try {
  const r = await fetch(\`\${base}/_gateway/health\`, { signal: AbortSignal.timeout(1000) })
  await r.body?.cancel()
  if (!r.ok) process.exit(0)
} catch {
  process.exit(0)
}

// \`claude --account X\` / \`--prefer X\`: the gateway turns X into the one
// account it names (/_gateway/resolve), and a /tc-acct/ or /tc-prefer/ prefix
// is its pin grammar. Asked of the gateway, never read from the accounts file:
// the file holds tokens, and the gateway's list is the one that routes. No
// name back -> no CC_SHIM_ROUTED -> the shim refuses the launch rather than
// run it on another account.
if (env.CC_SHIM_ACCOUNT) {
  let who = ""
  let failed = false
  let why = ""
  try {
    const r = await fetch(\`\${base}/_gateway/resolve?q=\${encodeURIComponent(env.CC_SHIM_ACCOUNT)}\`, { signal: AbortSignal.timeout(2000) })
    const text = (await r.text()).trim()
    if (r.ok) who = text
    else [failed, why] = [true, text]
  } catch {
    failed = true
  }
  if (failed) process.stderr.write(\`claude --account: \${why || "the gateway did not answer"}\\n\`)
  if (!who) process.exit(0)
  base = \`\${base}/\${env.CC_SHIM_ACCOUNT_SOFT ? "tc-prefer" : "tc-acct"}/\${who}\`
  env.CC_SHIM_ROUTED = who
}

env.ANTHROPIC_BASE_URL = base

// The doorman pass: satisfies Claude Code's own credential gate without being a
// credential. The gateway discards it and injects the routed account's real
// Bearer. Not ANTHROPIC_API_KEY — that flips API mode.
env.ANTHROPIC_AUTH_TOKEN = "gateway-doorman"

// Identity the wire keys on. Origin says "a terminal"; project is the cwd's
// name, the only thing a bare launch knows about which work it belongs to.
// Appended after anything the caller already set, newline-separated as
// Claude Code parses it.
const hdr = \`x-brain-origin: cli\\nx-brain-project: \${basename(env.PWD || process.cwd())}\`
env.ANTHROPIC_CUSTOM_HEADERS = env.ANTHROPIC_CUSTOM_HEADERS ? \`\${env.ANTHROPIC_CUSTOM_HEADERS}\\n\${hdr}\` : hdr

// What Claude Code turns off behind any base URL that is not Anthropic's, and
// this gateway carries (gateway/src/claude-env.ts says why each one). Only when
// unset: a value exported in the shell wins, and a settings.json \`env\` entry
// wins over both — Claude Code applies those over the launch environment.
const defaults = ${q(CLAUDE_ENV)}
for (const [k, v] of Object.entries(defaults)) if (!env[k]) env[k] = v

// An inherited OAuth token would outrank the base URL and leave a real
// credential in the environment — the thing routing through a wire removes.
env.CC_SHIM_UNSET = "CLAUDE_CODE_OAUTH_TOKEN ANTHROPIC_API_KEY"
env.CC_SHIM_CLAIM = "ak-gateway"
`
}

export type ShimState = { path: string; installed: boolean; rev: number | null; current: boolean }

/** Installed when either fragment is there; current only when the native one is, at this rev, alone. */
export function shimState(): ShimState {
  const path = fragmentPath()
  const legacy = legacyFragmentPath()
  if (!existsSync(path)) {
    return existsSync(legacy)
      ? { path: legacy, installed: true, rev: revOf(legacy), current: false }
      : { path, installed: false, rev: null, current: false }
  }
  const rev = revOf(path)
  return { path, installed: true, rev, current: rev === FRAGMENT_REV && !existsSync(legacy) }
}

function revOf(file: string): number | null {
  const m = readFileSync(file, "utf8").match(/\. rev (\d+)/)
  return m ? Number(m[1]) : null
}

export function shimOn(cfg: Config): ShimState {
  const dir = fragmentDir()
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true, mode: 0o700 })
  // Owner-only, as cc-shim's conf.d contract asks of every fragment (they may hold
  // tokens; this one holds only the doorman pass) — `cc-shim doctor` warns otherwise.
  // `mode` applies only to a new file, so an existing one is narrowed too.
  writeFileSync(fragmentPath(), renderFragment(cfg), { mode: 0o600 })
  chmodSync(fragmentPath(), 0o600)
  // The bash one sorts first and claims: left behind, it would take every launch.
  if (existsSync(legacyFragmentPath())) unlinkSync(legacyFragmentPath())
  return shimState()
}

export function shimOff(): ShimState {
  for (const f of [fragmentPath(), legacyFragmentPath()]) if (existsSync(f)) unlinkSync(f)
  return shimState()
}
